// motto.js
const motto = [
  "When one is young and eager to learn, he is like the sun at sunrise; when one is strong and eager to learn, he is like the sun at noon; when one is old and eager to learn, he is like the light of a bright candle ———— Liu Xiang",
  "Those who are good at making use of their spare time will achieve greater success ———— Hua Luogeng",
  "Failure is the ultimate test of perseverance ———— Bismarck",
  "If it is a rose, it will always bloom ———— Goethe",
  "Every setback or unfavorable change carries the seeds of an equal or greater advantage ———— Emerson",
  "There is a solution to every problem, and there is no such thing as an unsolvable problem ———— Edison",
  "People need truth just as a blind man needs a bright guide ———— Maxim Gorky",
  "Failure is also what I need. It is as valuable to me as success ———— Thomas Edison",
  "Look deep into your own heart, and you will find that all the miracles are in you ———— Francis Bacon",
  "A man can succeed in almost anything for which he has unlimited enthusiasm ———— Charles Schwab",
  "I walk slowly, but I never walk backwards ———— Abraham Lincoln",
  "Stay hungry, stay foolish ———— Steve Jobs",
  "The only way to do great work is to love what you do ———— Steve Jobs",
  "To be, or not to be, that is the question ———— Shakespeare",
  "All our dreams can come true, if we have the courage to pursue them ———— Walt Disney",
  "The future belongs to those who believe in the beauty of their dreams ———— Eleanor Roosevelt",
  // New mottos
  "Do not wait to strike till the iron is hot; but make it hot by striking ———— William Butler Yeats",
  "It always seems impossible until it’s done ———— Nelson Mandela",
  "In the middle of every difficulty lies opportunity ———— Albert Einstein",
  "What you get by achieving your goals is not as important as what you become by achieving your goals ———— Zig Ziglar",
  "Happiness depends upon ourselves ———— Aristotle",
  "Act as if what you do makes a difference. It does ———— William James",
  "Success is not final, failure is not fatal: It is the courage to continue that counts ———— Winston Churchill",
  "Dream big and dare to fail ———— Norman Vaughan",
  "Do what you can, with what you have, where you are ———— Theodore Roosevelt",
  "Your time is limited, so don’t waste it living someone else’s life ———— Steve Jobs",
  "Courage is grace under pressure ———— Ernest Hemingway",
  "Everything you’ve ever wanted is on the other side of fear ———— George Addair",
  "Believe you can and you’re halfway there ———— Theodore Roosevelt",
  "The best way to predict the future is to invent it ———— Alan Kay",
  "Opportunities don't happen, you create them ———— Chris Grosser",
  "Don’t let the fear of losing be greater than the excitement of winning ———— Robert Kiyosaki",
  "If you can dream it, you can do it ———— Walt Disney",
  "Hardships often prepare ordinary people for an extraordinary destiny ———— C.S. Lewis",
  "Don’t count the days, make the days count ———— Muhammad Ali",
  "If you’re going through hell, keep going ———— Winston Churchill",
  "Turn your wounds into wisdom ———— Oprah Winfrey",
  "Fall seven times and stand up eight ———— Japanese Proverb",
  "Success usually comes to those who are too busy to be looking for it ———— Henry David Thoreau",
  "Do not pray for an easy life, pray for the strength to endure a difficult one ———— Bruce Lee",
  "He who opens a school door, closes a prison ———— Victor Hugo",
  "Knowledge is power ———— Francis Bacon",
  "Education is the most powerful weapon which you can use to change the world ———— Nelson Mandela",
  "Wise men speak because they have something to say; fools because they have to say something ———— Plato",
  "The journey of a thousand miles begins with a single step ———— Lao Tzu",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us ———— Ralph Waldo Emerson",
  "Knowing yourself is the beginning of all wisdom ———— Aristotle",
  "He who has a why to live can bear almost any how ———— Friedrich Nietzsche",
  "The man who moves a mountain begins by carrying away small stones ———— Confucius",
  "Do one thing every day that scares you ———— Eleanor Roosevelt",
  "Strive not to be a success, but rather to be of value ———— Albert Einstein",
  "Don’t watch the clock; do what it does. Keep going ———— Sam Levenson",
  "You miss 100% of the shots you don’t take ———— Wayne Gretzky",
  "Whether you think you can or you think you can’t, you’re right ———— Henry Ford",
  "Limit your 'always' and your 'nevers' ———— Amy Poehler",
  "Action is the foundational key to all success ———— Pablo Picasso",
  "Everything has beauty, but not everyone sees it ———— Confucius",
  "Keep your face always toward the sunshine—and shadows will fall behind you ———— Walt Whitman",
  "The secret of getting ahead is getting started ———— Mark Twain",
  "Great minds discuss ideas; average minds discuss events; small minds discuss people ———— Eleanor Roosevelt",
  "The way to get started is to quit talking and begin doing ———— Walt Disney",
  "Opportunities multiply as they are seized ———— Sun Tzu",
  "Do not go where the path may lead, go instead where there is no path and leave a trail ———— Ralph Waldo Emerson",
  "Success is walking from failure to failure with no loss of enthusiasm ———— Winston Churchill",
  "If opportunity doesn’t knock, build a door ———— Milton Berle",
  "Everything you can imagine is real ———— Pablo Picasso",
];
