// motto.js
const motto = [
  "When one is young and eager to learn, he is like the sun at sunrise; when one is strong and eager to learn, he is like the sun at noon; when one is old and eager to learn, he is like the light of a bright candle ———— Liu Xiang",
  "Those who are good at making use of their spare time will achieve greater success ———— Hua Luogeng",
  "Failure is the ultimate test of perseverance ———— Bismarck",
  "If it is a rose, it will always bloom ———— Goethe",
  "Every setback or unfavorable change carries the seeds of an equal or greater advantage ———— Emerson",
  "There is a solution to every problem, and there is no such thing as an unsolvable problem ———— Edison",
  "People need truth just as a blind man needs a bright guide ———— Maxim Gorky",
  "Failure is also what I need. It is as valuable to me as success ———— Thomas Edison",
  "Look deep into your own heart, and you will find that all the miracles are in you ———— Francis Bacon",
  "A man can succeed in almost anything for which he has unlimited enthusiasm ———— Charles Schwab",
  "I walk slowly, but I never walk backwards ———— Abraham Lincoln",
  "Stay hungry, stay foolish ———— Steve Jobs",
  "The only way to do great work is to love what you do ———— Steve Jobs",
  "To be, or not to be, that is the question ———— Shakespeare",
  "All our dreams can come true, if we have the courage to pursue them ———— Walt Disney",
  "The future belongs to those who believe in the beauty of their dreams ———— Eleanor Roosevelt",
  // New mottos
  "Do not wait to strike till the iron is hot; but make it hot by striking ———— William Butler Yeats",
  "It always seems impossible until it’s done ———— Nelson Mandela",
  "In the middle of every difficulty lies opportunity ———— Albert Einstein",
  "What you get by achieving your goals is not as important as what you become by achieving your goals ———— Zig Ziglar",
  "Happiness depends upon ourselves ———— Aristotle",
  "Act as if what you do makes a difference. It does ———— William James",
  "Success is not final, failure is not fatal: It is the courage to continue that counts ———— Winston Churchill",
  "Dream big and dare to fail ———— Norman Vaughan",
  "Do what you can, with what you have, where you are ———— Theodore Roosevelt",
  "Your time is limited, so don’t waste it living someone else’s life ———— Steve Jobs",
  "Courage is grace under pressure ———— Ernest Hemingway",
  "Everything you’ve ever wanted is on the other side of fear ———— George Addair",
  "Believe you can and you’re halfway there ———— Theodore Roosevelt",
  "The best way to predict the future is to invent it ———— Alan Kay",
  "Opportunities don't happen, you create them ———— Chris Grosser",
  "Don’t let the fear of losing be greater than the excitement of winning ———— Robert Kiyosaki",
  "If you can dream it, you can do it ———— Walt Disney",
  "Hardships often prepare ordinary people for an extraordinary destiny ———— C.S. Lewis",
  "Don’t count the days, make the days count ———— Muhammad Ali",
  "If you’re going through hell, keep going ———— Winston Churchill",
  "Turn your wounds into wisdom ———— Oprah Winfrey",
  "Fall seven times and stand up eight ———— Japanese Proverb",
  "Success usually comes to those who are too busy to be looking for it ———— Henry David Thoreau",
  "Do not pray for an easy life, pray for the strength to endure a difficult one ———— Bruce Lee",
  "He who opens a school door, closes a prison ———— Victor Hugo",
  "Knowledge is power ———— Francis Bacon",
  "Education is the most powerful weapon which you can use to change the world ———— Nelson Mandela",
  "Wise men speak because they have something to say; fools because they have to say something ———— Plato",
  "The journey of a thousand miles begins with a single step ———— Lao Tzu",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us ———— Ralph Waldo Emerson",
  "Knowing yourself is the beginning of all wisdom ———— Aristotle",
  "He who has a why to live can bear almost any how ———— Friedrich Nietzsche",
  "The man who moves a mountain begins by carrying away small stones ———— Confucius",
  "Do one thing every day that scares you ———— Eleanor Roosevelt",
  "Strive not to be a success, but rather to be of value ———— Albert Einstein",
  "Don’t watch the clock; do what it does. Keep going ———— Sam Levenson",
  "You miss 100% of the shots you don’t take ———— Wayne Gretzky",
  "Whether you think you can or you think you can’t, you’re right ———— Henry Ford",
  "Limit your 'always' and your 'nevers' ———— Amy Poehler",
  "Action is the foundational key to all success ———— Pablo Picasso",
  "Everything has beauty, but not everyone sees it ———— Confucius",
  "Keep your face always toward the sunshine—and shadows will fall behind you ———— Walt Whitman",
  "The secret of getting ahead is getting started ———— Mark Twain",
  "Great minds discuss ideas; average minds discuss events; small minds discuss people ———— Eleanor Roosevelt",
  "The way to get started is to quit talking and begin doing ———— Walt Disney",
  "Opportunities multiply as they are seized ———— Sun Tzu",
  "Do not go where the path may lead, go instead where there is no path and leave a trail ———— Ralph Waldo Emerson",
  "Success is walking from failure to failure with no loss of enthusiasm ———— Winston Churchill",
  "If opportunity doesn’t knock, build a door ———— Milton Berle",
  "Everything you can imagine is real ———— Pablo Picasso",
  // 100 new mottos start here
  "The purpose of our lives is to be happy ———— Dalai Lama",
  "Life is what happens when you're busy making other plans ———— John Lennon",
  "Get busy living or get busy dying ———— Stephen King",
  "You only live once, but if you do it right, once is enough ———— Mae West",
  "Many of life's failures are people who did not realize how close they were to success when they gave up ———— Thomas A. Edison",
  "If you want to live a happy life, tie it to a goal, not to people or things ———— Albert Einstein",
  "Never let the fear of striking out keep you from playing the game ———— Babe Ruth",
  "Not how long, but how well you have lived is the main thing ———— Seneca",
  "The whole secret of a successful life is to find out what is one’s destiny to do, and then do it ———— Henry Ford",
  "The big lesson in life, baby, is never be scared of anyone or anything ———— Frank Sinatra",
  "Life is not a problem to be solved, but a reality to be experienced ———— Soren Kierkegaard",
  "The unexamined life is not worth living ———— Socrates",
  "The way I see it, if you want the rainbow, you gotta put up with the rain ———— Dolly Parton",
  "Everything negative – pressure, challenges – is all an opportunity for me to rise ———— Kobe Bryant",
  "Life is like riding a bicycle. To keep your balance, you must keep moving ———— Albert Einstein",
  "Life is really simple, but we insist on making it complicated ———— Confucius",
  "In three words I can sum up everything I've learned about life: it goes on ———— Robert Frost",
  "Life is ten percent what happens to you and ninety percent how you respond to it ———— Charles Swindoll",
  "To live is the rarest thing in the world. Most people exist, that is all ———— Oscar Wilde",
  "It is not length of life, but depth of life ———— Ralph Waldo Emerson",
  "Life is a flower of which love is the honey ———— Victor Hugo",
  "It is better to be hated for what you are than to be loved for what you are not ———— Andre Gide",
  "Dost thou love life? Then do not squander time, for that is the stuff life is made of ———— Benjamin Franklin",
  "Life would be tragic if it weren’t funny ———— Stephen Hawking",
  "Don’t gain the world and lose your soul, wisdom is better than silver or gold ———— Bob Marley",
  "Be happy for this moment. This moment is your life ———— Omar Khayyam",
  "The two most important days in your life are the day you are born and the day you find out why ———— Mark Twain",
  "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose ———— Dr. Seuss",
  "The more you praise and celebrate your life, the more there is in life to celebrate ———— Oprah Winfrey",
  "If you don't design your own life plan, chances are you'll fall into someone else's plan. And guess what they have planned for you? Not much ———— Jim Rohn",
  "We are what we repeatedly do. Excellence, then, is not an act, but a habit ———— Aristotle",
  "The only impossible journey is the one you never begin ———— Tony Robbins",
  "The person who says it cannot be done should not interrupt the person who is doing it ———— Chinese Proverb",
  "You can't use up creativity. The more you use, the more you have ———— Maya Angelou",
  "Build your own dreams, or someone else will hire you to build theirs ———— Farrah Gray",
  "I find that the harder I work, the more luck I seem to have ———— Thomas Jefferson",
  "Don't be afraid to give up the good to go for the great ———— John D. Rockefeller",
  "What seems to us as bitter trials are often blessings in disguise ———— Oscar Wilde",
  "I have not failed. I've just found 10,000 ways that won't work ———— Thomas Edison",
  "If you're offered a seat on a rocket ship, don't ask what seat! Just get on ———— Sheryl Sandberg",
  "I would rather die of passion than of boredom ———— Vincent van Gogh",
  "A person who never made a mistake never tried anything new ———— Albert Einstein",
  "It is never too late to be what you might have been ———— George Eliot",
  "If you do what you’ve always done, you’ll get what you’ve always gotten ———— Tony Robbins",
  "Twenty years from now you will be more disappointed by the things that you didn’t do than by the ones you did do ———— Mark Twain",
  "The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will ———— Vince Lombardi",
  "The mind is everything. What you think you become ———— Buddha",
  "Eighty percent of success is showing up ———— Woody Allen",
  "Winning isn’t everything, but wanting to win is ———— Vince Lombardi",
  "I am not a product of my circumstances. I am a product of my decisions ———— Stephen Covey",
  "Either you run the day, or the day runs you ———— Jim Rohn",
  "The best revenge is massive success ———— Frank Sinatra",
  "People often say that motivation doesn’t last. Well, neither does bathing. That’s why we recommend it daily ———— Zig Ziglar",
  "Life shrinks or expands in proportion to one’s courage ———— Anais Nin",
  "There is only one way to avoid criticism: do nothing, say nothing, and be nothing ———— Aristotle",
  "The most difficult thing is the decision to act, the rest is merely tenacity ———— Amelia Earhart",
  "Every strike brings me closer to the next home run ———— Babe Ruth",
  "Definiteness of purpose is the starting point of all achievement ———— W. Clement Stone",
  "We must be willing to let go of the life we have planned, so as to have the life that is waiting for us ———— Joseph Campbell",
  "Nothing will work unless you do ———— Maya Angelou",
  "Go confidently in the direction of your dreams! Live the life you’ve imagined ———— Henry David Thoreau",
  "Believe and act as if it were impossible to fail ———— Charles Kettering",
  "The question isn’t who is going to let me; it’s who is going to stop me ———— Ayn Rand",
  "Perfection is not attainable, but if we chase perfection we can catch excellence ———— Vince Lombardi",
  "A goal is a dream with a deadline ———— Napoleon Hill",
  "We can't help everyone, but everyone can help someone ———— Ronald Reagan",
  "Whatever the mind of man can conceive and believe, it can achieve ———— Napoleon Hill",
  "Logic will get you from A to B. Imagination will take you everywhere ———— Albert Einstein",
  "That which does not kill us makes us stronger ———— Friedrich Nietzsche",
  "An investment in knowledge pays the best interest ———— Benjamin Franklin",
  "There are no shortcuts to any place worth going ———— Beverly Sills",
  "No one can make you feel inferior without your consent ———— Eleanor Roosevelt",
  "The successful warrior is the average man, with laser-like focus ———— Bruce Lee",
  "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment ———— Ralph Waldo Emerson",
  "If you are not willing to risk the usual, you will have to settle for the ordinary ———— Jim Rohn",
  "The road to success and the road to failure are almost exactly the same ———— Colin R. Davis",
  "It is our choices that show what we truly are, far more than our abilities ———— J.K. Rowling",
  "The only limit to our realization of tomorrow will be our doubts of today ———— Franklin D. Roosevelt",
  "Change your thoughts and you change your world ———— Norman Vincent Peale",
  "It does not matter how slowly you go as long as you do not stop ———— Confucius",
  "Either write something worth reading or do something worth writing ———— Benjamin Franklin",
  "The best time to plant a tree was 20 years ago. The second best time is now ———— Chinese Proverb",
  "What we think, we become ———— Buddha",
  "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. And the only way to do great work is to love what you do. ———— Steve Jobs",
  "A creative man is motivated by the desire to achieve, not by the desire to beat others ———— Ayn Rand",
  "The best way to have a good idea is to have a lot of ideas ———— Linus Pauling",
  "The greatest glory in living lies not in never falling, but in rising every time we fall ———— Nelson Mandela",
  "The only thing we have to fear is fear itself ———— Franklin D. Roosevelt",
  "To handle yourself, use your head; to handle others, use your heart ———— Eleanor Roosevelt",
  "Too many of us are not living our dreams because we are living our fears ———— Les Brown",
  "Whatever you are, be a good one ———— Abraham Lincoln",
  "If you want to lift yourself up, lift up someone else ———— Booker T. Washington",
  "You must be the change you wish to see in the world ———— Mahatma Gandhi",
  "The dreamers are the saviors of the world ———— James Allen",
  "It is better to fail in originality than to succeed in imitation ———— Herman Melville",
  "A champion is afraid of losing. Everyone else is afraid of winning ———— Billie Jean King",
  "The path to success is to take massive, determined action ———— Tony Robbins",
  "Fortune favors the bold ———— Virgil"
];
