// motto.js
const motto = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "When one is young and eager to learn, he is like the sun at sunrise; when one is strong and eager to learn, he is like the sun at noon; when one is old and eager to learn, he is like the light of a bright candle ———— Liu Xiang",
  "Those who are good at making use of their spare time will achieve greater success ———— Hua Luogeng",
  "Failure is the ultimate test of perseverance ———— Bismarck",
  "If it is a rose, it will always bloom ———— Goethe",
  "Every setback or unfavorable change carries the seeds of an equal or greater advantage ———— Emerson",
  "There is a solution to every problem, and there is no such thing as an unsolvable problem ———— Edison",
  "People need truth just as a blind man needs a bright guide ———— Maxim Gorky",
  "Failure is also what I need. It is as valuable to me as success ———— Thomas Edison",
  "Look deep into your own heart, and you will find that all the miracles are in you ———— Francis Bacon",
  "A man can succeed in almost anything for which he has unlimited enthusiasm ———— Charles Schwab",
  "I walk slowly, but I never walk backwards ———— Abraham Lincoln",
  "Stay hungry, stay foolish ———— Steve Jobs",
  "The only way to do great work is to love what you do ———— Steve Jobs",
  "To be, or not to be, that is the question ———— Shakespeare",
  "All our dreams can come true, if we have the courage to pursue them ———— Walt Disney",
  "The future belongs to those who believe in the beauty of their dreams ———— Eleanor Roosevelt",
];
